name: Deploy Using Shared Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    uses: seannguyn/actions/.github/workflows/serverless.yaml@main
    with:
      docker_repo: ${{ vars.DOCKER_REPO }} 
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
